apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-task
  template:
    metadata:
      labels:
        app: hotel-task
    spec:
      containers:
        - name: hotel-task-container
          image: ghcr.io/alisafarpour/hotel-task:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: hotel-task-service
spec:
  selector:
    app: hotel-task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
